name: Generate pacman animation

on:
  schedule:
    - cron: "* */12 * * *" # roda a cada 12 horas
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Baixa o repositório
      - uses: actions/checkout@v3

      # 2. Gera o Pacman Contribution Graph
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3. Cria a pasta dist (a Action já gera o arquivo dentro dela)
      - name: Prepare dist folder
        run: mkdir -p dist

      # 4. Envia para a branch "output"
      - name: Push pacman-contribution-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
